/* 香料素材谱（由 .tools/gen_assets.js 自动生成，2026-09-21 04:59）
   三维就位 34 味 · 仅正视图 19 味 · 占位 0 味
   游戏侧：XiangYe 启动时合并本表；未列名者自动退墨线占位，且不发起任何请求 */
window.SPICE_ASSETS = {
  ready: {
    huajiao:{ model:'../huajiao/models/model.glb', image:'../huajiao/models/front.png' },
    huixiang:{ model:'../huixiang/models/model.glb', image:'../huixiang/models/front.png' },
    aicao:{ model:'../aicao/models/aicao.glb' },
    cangzhu:{ model:'../cangzhu/models/cangzhu.glb' },
    shengjiang:{ model:'../shengjiang/models/shengjiang.glb' },
    wuzhuyu:{ model:'../wuzhuyu/models/wuzhuyu.glb' },
    wujiapi:{ model:'../wujiapi/models/wujiapi.glb' },
    gansong:{ model:'../gansong/models/gansong.glb' },
    jingjie:{ model:'../jingjie/models/jingjie.glb' },
    bohe:{ model:'../bohe/models/bohe.glb' },
    peilan:{ model:'../peilan/models/peilan.glb' },
    baizhi:{ model:'../baizhi/models/baizhi.glb' },
    xinyi:{ model:'../xinyi/models/xinyi.glb' },
    moli:{ model:'../moli/models/model.glb', image:'../moli/models/front.png' },
    luohanguo:{ model:'../luohanguo/models/luohanguo.glb' },
    furong:{ model:'../furong/models/furong.glb' },
    zisu:{ model:'../zisu/models/zisu.glb' },
    chenpi:{ model:'../chenpi/models/chenpi.glb' },
    huoxiang:{ model:'../huoxiang/models/huoxiang.glb' },
    liangjiang:{ model:'../liangjiang/models/liangjiang.glb' },
    jinyinhua:{ model:'../jinyinhua/models/jinyinhua.glb' },
    xiangmaocao:{ model:'../xiangmaocao/models/xiangmaocao.glb' },
    jianghuang:{ model:'../jianghuang/models/jianghuang.glb' },
    bajiao:{ model:'../bajiao/models/bajiao.glb' },
    caoguo:{ model:'../caoguo/models/model.glb', image:'../caoguo/models/front.png' },
    hujiao:{ model:'../hujiao/models/hujiao.glb' },
    dingxiang:{ model:'../dingxiang/models/dingxiang.glb' },
    rougui:{ model:'../rougui/models/rougui.glb' },
    baidoukou:{ model:'../baikou/models/baikou.glb' },
    tanxiang:{ model:'../tanxiang/models/tanxiang.glb' },
    yuegui:{ model:'../yuegui/models/yuegui.glb' },
    niuzhi:{ model:'../niuzhi/models/niuzhi.glb' },
    bailixiang:{ model:'../bailixiang/models/bailixiang.glb' },
    midiexiang:{ model:'../midiexiang/models/midiexiang.glb' },
  },
  image: {
    hangju:{ image:'../hangju/models/front.png' },
    guihua:{ image:'../guihua/models/front.png' },
    meigui:{ image:'../meigui/models/front.png' },
    zhizi:{ image:'../zhizi/models/front.png' },
    meihua:{ image:'../meihua/models/front.png' },
    foshou:{ image:'../foshou/models/front.png' },
    sharen:{ image:'../sharen/models/front.png' },
    yujin:{ image:'../yujin/models/front.png' },
    sumu:{ image:'../sumu/models/front.png' },
    bibo:{ image:'../bibo/models/front.png' },
    linglingxiang:{ image:'../linglingxiang/models/front.png' },
    muxiang:{ image:'../muxiang/models/front.png' },
    chenxiang:{ image:'../chenxiang/models/front.png' },
    longnao:{ image:'../longnao/models/front.png' },
    ruxiang:{ image:'../ruxiang/models/front.png' },
    moyao:{ image:'../moyao/models/front.png' },
    anxixiang:{ image:'../anxixiang/models/front.png' },
    suhexiang:{ image:'../suhexiang/models/front.png' },
    jiangzhenxiang:{ image:'../jiangzhenxiang/models/front.png' },
  }
};
