/* 香料素材谱（由 .tools/gen_assets.js 自动生成，2026-09-27 16:59）
   三维就位 71 味 · 仅正视图 1 味 · 占位 0 味
   游戏侧：XiangYe 启动时合并本表；未列名者自动退墨线占位，且不发起任何请求 */
window.SPICE_ASSETS = {
  ready: {
    huajiao:{ model:'../huajiao/models/huajiao.glb', image:'../huajiao/models/front.png' },
    huixiang:{ model:'../huixiang/models/model.glb', image:'../huixiang/models/front.png' },
    aicao:{ model:'../aicao/models/aicao.glb' },
    cangzhu:{ model:'../cangzhu/models/cangzhu.glb' },
    shengjiang:{ model:'../shengjiang/models/shengjiang.glb' },
    wuzhuyu:{ model:'../wuzhuyu/models/wuzhuyu.glb' },
    wujiapi:{ model:'../wujiapi/models/wujiapi.glb' },
    gansong:{ model:'../gansong/models/gansong.glb' },
    jingjie:{ model:'../jingjie/models/jingjie.glb' },
    bohe:{ model:'../bohe/models/bohe.glb' },
    peilan:{ model:'../peilan/models/peilan.glb' },
    baizhi:{ model:'../baizhi/models/baizhi.glb' },
    xinyi:{ model:'../xinyi/models/xinyi.glb' },
    moli:{ model:'../moli/models/model.glb', image:'../moli/models/front.png' },
    hangju:{ model:'../hangju/models/hangju.glb', image:'../hangju/models/front.png' },
    guihua:{ model:'../guihua/models/guihua.glb', image:'../guihua/models/front.png' },
    meigui:{ model:'../meigui/models/model.glb', image:'../meigui/models/front.png' },
    zhizi:{ model:'../zhizi/models/zhizi.glb', image:'../zhizi/models/front.png' },
    meihua:{ model:'../meihua/models/model.glb', image:'../meihua/models/front.png' },
    foshou:{ model:'../foshou/models/foshou.glb', image:'../foshou/models/front.png' },
    luohanguo:{ model:'../luohanguo/models/luohanguo.glb' },
    furong:{ model:'../furong/models/furong.glb' },
    zisu:{ model:'../zisu/models/zisu.glb' },
    chenpi:{ model:'../chenpi/models/chenpi.glb' },
    huoxiang:{ model:'../huoxiang/models/huoxiang.glb' },
    liangjiang:{ model:'../liangjiang/models/liangjiang.glb' },
    jinyinhua:{ model:'../jinyinhua/models/jinyinhua.glb' },
    xiangmaocao:{ model:'../xiangmaocao/models/xiangmaocao.glb' },
    jianghuang:{ model:'../jianghuang/models/jianghuang.glb' },
    bajiao:{ model:'../bajiao/models/bajiao.glb' },
    caoguo:{ model:'../caoguo/models/caoguo.glb', image:'../caoguo/models/front.png' },
    sharen:{ model:'../sharen/models/sharen.glb', image:'../sharen/models/front.png' },
    yujin:{ model:'../yujin/models/yujin.glb', image:'../yujin/models/front.png' },
    sumu:{ model:'../sumu/models/sumu.glb', image:'../sumu/models/front.png' },
    bibo:{ model:'../bibo/models/bibo.glb', image:'../bibo/models/front.png' },
    linglingxiang:{ model:'../linglingxiang/models/linglingxiang.glb', image:'../linglingxiang/models/front.png' },
    hujiao:{ model:'../hujiao/models/hujiao.glb' },
    dingxiang:{ model:'../dingxiang/models/dingxiang.glb' },
    rougui:{ model:'../rougui/models/rougui.glb' },
    baidoukou:{ model:'../baikou/models/baikou.glb' },
    tanxiang:{ model:'../tanxiang/models/tanxiang.glb' },
    chenxiang:{ model:'../chenxiang/models/chenxiang.glb', image:'../chenxiang/models/front.png' },
    longnao:{ model:'../longnao/models/model.glb', image:'../longnao/models/front.png' },
    ruxiang:{ model:'../ruxiang/models/ruxiang.glb', image:'../ruxiang/models/front.png' },
    moyao:{ model:'../moyao/models/moyao.glb', image:'../moyao/models/front.png' },
    anxixiang:{ model:'../anxixiang/models/anxixiang.glb', image:'../anxixiang/models/front.png' },
    suhexiang:{ model:'../suhexiang/models/suhexiang.glb', image:'../suhexiang/models/front.png' },
    jiangzhenxiang:{ model:'../jiangzhenxiang/models/jiangzhenxiang.glb', image:'../jiangzhenxiang/models/front.png' },
    yuegui:{ model:'../yuegui/models/yuegui.glb' },
    niuzhi:{ model:'../niuzhi/models/niuzhi.glb' },
    bailixiang:{ model:'../bailixiang/models/bailixiang.glb' },
    midiexiang:{ model:'../midiexiang/models/midiexiang.glb' },
    gancao:{ model:'../gancao/models/gancao.glb' },
    xiangru:{ model:'../xiangru/models/xiangru.glb' },
    xiangfu:{ model:'../xiangfu/models/xiangfu.glb' },
    gaoben:{ model:'../gaoben/models/gaoben.glb' },
    xixin:{ model:'../xixin/models/xixin.glb' },
    qianghuo:{ model:'../qianghuo/models/qianghuo.glb' },
    duzhong:{ model:'../duzhong/models/duzhong.glb' },
    guizhi:{ model:'../guizhi/models/guizhi.glb' },
    chuanxiong:{ model:'../chuanxiong/models/chuanxiong.glb' },
    shannai:{ model:'../shannai/models/shannai.glb' },
    caodoukou:{ model:'../caodoukou/models/caodoukou.glb' },
    hongdoukou:{ model:'../hongdoukou/models/hongdoukou.glb' },
    yizhi:{ model:'../yizhi/models/yizhi.glb' },
    xiangyuan:{ model:'../xiangyuan/models/xiangyuan.glb' },
    luolei:{ model:'../luolei/models/luolei.glb' },
    lamei:{ model:'../lamei/models/lamei.glb' },
    daidaihua:{ model:'../daidaihua/models/daidaihua.glb' },
    ainaixiang:{ model:'../ainaixiang/models/ainaixiang.glb' },
    zanghonghua:{ model:'../zanghonghua/models/zanghonghua.glb' },
  },
  image: {
    muxiang:{ image:'../muxiang/models/front.png' },
  }
};
